### ISSUE TITLE
My new repo

### ISSUE THREAD

**Issue by L1cardo** [nihalsharma/Clock-Bar#11]
I don't know why the origin developer @nihalsharma has not been active on GitHub for over 10 months, so I created a new [repo](https://github.com/L1cardo/Clock-Bar) of this app.
Fixed the issue #3 #4 #6 #7 #8 #10 

I should fork this repo instead of creating new one , but there is some reason why I did no : 
 1. The author has not been active for over 10 month. There is no maintainer now.
 2. I want to add this to 'homebrew-cask' which require the ownership of the app.

If the origin developer @nihalsharma returns and is not OK with my creating new repo, I will delete immediately.

**Comment by nihalsharma** [comment]
Hi, I have already raised a PR for homebrew-cask. I will be working on few of the features requested.

[PR Link](https://github.com/Homebrew/homebrew-cask/pull/58149)

Please close the new repo which you have created under your name. Thanks

**Comment by L1cardo** [comment]
Hi! It is good to have you back !
The community have done so many error correction to the clock-bar app, please have a look and merge the requests!
Fixed so many issues.
Once you fix the issues and merge all the requests , I will delete my repo and fork yours.
thanks
