### ISSUE TITLE
[Enhancement] More colour options

### ISSUE THREAD

**Issue by cristiean** [nihalsharma/Clock-Bar#13]
This is app idea is great! I've been using since I got my TouchBar MacBook Pro, and don't see using my Mac otherwise. 

However, since the beginning I felt the need for more colour choice. In the end, I made my own [repo](https://github.com/cristiean/Clock-Bar-Retro-Theme) with retro colours, which I love. (This was my first ever open-source GitHub thing I've ever done, so apologies if I've stepped over any unwritten rules)

However, I still think that having a colour wheel, or (if possible) integrating Apple's colour choice thingy (with crayons, the colour wheel and the slides) would be a truly amazing addition.

**Comment by cristiean** [comment]
This might be useful? NSColourPickerTouchBarItem would be a great addition. The only problem I encounter is that I don't know where to input the returned NSColor https://spin.atomicobject.com/2017/11/18/nstouchbar-storyboards/

**Comment by nihalsharma** [comment]
Will add it in a subsequent release. Thanks.
