### ISSUE TITLE
It is Blocked Out When I Open Media

### ISSUE THREAD

**Issue by satriahrh** [nihalsharma/Clock-Bar#18]
***Step to reproduce***
- Start the Clock Bar, it is should be available at the most right of the small touch bar.
- Play a media (e.g. Spotify) that will trigger the media icon on the touch bar to be appeared at the most right.

***Expected Behaviour***
Both clock and media icon appearing side to side

***Actual Behaviour***
Media icon is appearing buth clock bar is not appearing

**Comment by nihalsharma** [comment]
These apps overwrite the icon on the right. That is normal behavior on opening the media apps. I am not sure how to make the clock bar permanently fixed. Making it permanent is not what the apple would allow. Thanks
