### ISSUE TITLE
Conflict with TouchBar App Switcher

### ISSUE THREAD

**Issue by hani-q** [nihalsharma/Clock-Bar#2]
Hi,

Had  [TB App switcher](https://hazeover.com/touchswitcher.html) already installed. Installing this caused it to stop and not show up on TouchBar. Relaunching TB App switcher makes the clock stop.

**Comment by homeslicesolutions-zz** [comment]
I have the same problem for me except that it happens when I turn on Spotify or any "now playing" that comes up.  Whenever that happens then the clock disappears

**Comment by nihalsharma** [comment]
@hani-q  - Installing Clock Bar app will not stop the other apps from working, but yes, the other app's icon will disappear. The first button(among the 5) from the left is the only floating position which can be taken over by any app that you install. All the apps will compete for this position only. So, the last installed app will get this position. I hope you get it.

@homeslicesolutions - When running Spotify or Apple music, their icons take over. But the Clock Bar does not exist. It is there. I will have to figure out a way to stop the clock to hide.
