### ISSUE TITLE
Clock Bar fails to launch correctly on Mac OS Catalina 10.15.4

### ISSUE THREAD

**Issue by davecahill** [nihalsharma/Clock-Bar#21]
**Steps taken:**

* Installed via brew, `brew cask install clock-bar` (`brew info clock-bar` shows version as `clock-bar: 1.0,1801968`)
* Launched Clock Bar app
* App screen shows for a second and disappears
* Searching for clock bar in[ Console|https://support.apple.com/guide/console/welcome/mac] shows the following message:
```
default	15:50:41.909051+0900	Clock Bar	LSExceptions shared instance invalidated for timeout.
```

**Comment by nihalsharma** [comment]
Hey, I am on  Mac OS Catalina 10.15.6 (19G2021). Have tried installing it multiple time. It works fine.

**Comment by bcashlol** [comment]
On MacOS 10.15.6, I run clock-bar after install via `brew cask install clock-bar`. The app runs, and I can view preferences, but the clock does not appear on the touch bar. 

Is there another step needed to make the app visible on the touch bar, or is this a bug?

**Comment by davecahill** [comment]
I'm now on 10.15.6 too. Yesterday I observed the same as @bcashlol - runs, can view preferences, no clock in touch bar. I reinstalled just now via ```brew reinstall clock-bar```, launched, and app is visible in Activity Monitor but doesn't show on menu bar or task switcher, and no app in touch bar. If you'd like me to do any debugging steps, just let me know!

**Comment by nihalsharma** [comment]
Closing it as I have tried installing it on different MacOs version, all are working fine for me. The app works fine on the latest version 11.0.
